openapi: 3.0.3
info:
  title: apps-training RESTful API
  version: 0.0.1
  description: OpenAPI definition file for impulse-apps
  contact:
    name: Impulse
servers:
  - url: /impulse-apps-training
tags:
  - name: root
  - name: employee
    description: API on employee
components:
  schemas:
    EmployeePostRequestBody:
      type: object
      description: Post request body to create a new employee
      properties:
        name:
          type: string
        description:
          type: string
    EmployeePutRequestBody:
      type: object
      description: Post request body to create a new employee
      properties:
        description:
          type: string
    Employee:
      type: object
      description: Basic response with application status code
      properties:
        employeeId:
          type: string
        name:
          type: string
        description:
          type: string
    Employees:
      type: array
      description: list of employee
      items:
        $ref: '#/components/schemas/Employee'
paths:
  /:
    get:
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./definitions/common.yaml#/components/schemas/BasicResponse"
              examples:
                res:
                  value:
                    appStatusCode: 200
                    description: Success
      description: Test server health
      tags:
        - root
      security: []
  /employees:
    post:
      operationId: post_employees
      tags:
        - employee
      description: create a new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeePostRequestBody'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller
    get:
      operationId: get_employees
      tags:
        - employee
      description: get all employees
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller
  /employees/{employeeId}:
    parameters:
      - name: employeeId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: get_employee
      tags:
        - employee
      description: Get a list of action recommendation by targetType and targetId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        default:
          description: Unexpected error
      x-openapi-router-controller: implemented.controllers.employee_controller
    put:
      operationId: put_employee
      tags:
        - employee
      description: update request
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeePutRequestBody"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        default:
          description: Unexpected error
      x-openapi-router-controller: implemented.controllers.employee_controller
    delete:
      operationId: delete_employee
      tags:
        - employee
      description: Delete a list of action recommendation by targetType and targetId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        default:
          description: Unexpected error
      x-openapi-router-controller: implemented.controllers.employee_controller
