openapi: 3.0.3
info:
  title: apps-training RESTful API
  version: 0.0.1
  description: OpenAPI definition file for impulse-apps
  contact:
    name: Impulse
servers:
  - url: /impulse-apps-training
tags:
  - name: root
  - name: employee
    description: API on employee
components:
  schemas:
    EmployeePostRequestBody:
      type: object
      description: Post request body to create a new employee
      properties:
        name:
          type: string
        department:
          type: string
        team:
          type: string
    EmployeePutRequestBody:
      type: object
      description: Put request body to update an employee
      properties:
        omitted:
          type: boolean
        participate:
          type: boolean
    Employee:
      type: object
      description: Basic response with application status code
      properties:
        name:
          type: string
        department:
          type: string
        team:
          type: string
        omitted:
          type: boolean
        participate:
          type: boolean
    Employees:
      type: array
      description: list of employee
      items:
        $ref: '#/components/schemas/Employee'
paths:
  /:
    get:
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./definitions/common.yaml#/components/schemas/BasicResponse"
              examples:
                res:
                  value:
                    appStatusCode: 200
                    description: Success
      description: Test server health
      tags:
        - root
      security: []

  /employees:
    get:
      operationId: get_employees
      tags:
        - employee
      description: get employees under several conditions
      parameters:
        - in: query
          name: random_get
          schema:
            type: boolean
            description: select an employee at random
        - in: query
          name: participant
          schema:
            type: boolean
            description: get the participants in the online lunch meeting
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller

    post:
      operationId: post_employees
      tags:
        - employee
      description: create a new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeePostRequestBody'
      responses:
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller

  /employees/{name}:
    parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string

    put:
      operationId: put_employee_by_name
      tags:
        - employee
      description: update omittetd and participate for the employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeePutRequestBody'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller

    delete:
      operationId: delete_employee
      tags:
        - employee
      description: Delete a list of action recommendation by targetType and targetId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        default:
          description: Unexpected Error
      x-openapi-router-controller: implemented.controllers.employee_controller

    get:
      operationId: get_employee
      tags:
        - employee
      description: Get a list of action recommendation by targetType and targetId
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        default:
          description: Unexpected error
      x-openapi-router-controller: implemented.controllers.employee_controller


