version: "3.7"

services:
  cassandra:
    image: cassandra:3.11.5
    container_name: cassandra
    networks:
      - impulse
    volumes:
      - cassandra-volume:/var/lib/cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo


networks:
  impulse:
    driver: bridge

volumes:
  cassandra-volume:
    driver: local
