# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from base.models.base_model_ import Model
from base import util


class EmployeePutRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, omitted=None, participate=None):  # noqa: E501
        """EmployeePutRequestBody - a model defined in OpenAPI

        :param omitted: The omitted of this EmployeePutRequestBody.  # noqa: E501
        :type omitted: bool
        :param participate: The participate of this EmployeePutRequestBody.  # noqa: E501
        :type participate: bool
        """
        self.openapi_types = {
            'omitted': bool,
            'participate': bool
        }

        self.attribute_map = {
            'omitted': 'omitted',
            'participate': 'participate'
        }

        self._omitted = omitted
        self._participate = participate

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeePutRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeePutRequestBody of this EmployeePutRequestBody.  # noqa: E501
        :rtype: EmployeePutRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def omitted(self):
        """Gets the omitted of this EmployeePutRequestBody.


        :return: The omitted of this EmployeePutRequestBody.
        :rtype: bool
        """
        return self._omitted

    @omitted.setter
    def omitted(self, omitted):
        """Sets the omitted of this EmployeePutRequestBody.


        :param omitted: The omitted of this EmployeePutRequestBody.
        :type omitted: bool
        """

        self._omitted = omitted

    @property
    def participate(self):
        """Gets the participate of this EmployeePutRequestBody.


        :return: The participate of this EmployeePutRequestBody.
        :rtype: bool
        """
        return self._participate

    @participate.setter
    def participate(self, participate):
        """Sets the participate of this EmployeePutRequestBody.


        :param participate: The participate of this EmployeePutRequestBody.
        :type participate: bool
        """

        self._participate = participate
