# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from base.models.base_model_ import Model
from base import util


class EmployeePostRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None):  # noqa: E501
        """EmployeePostRequestBody - a model defined in OpenAPI

        :param name: The name of this EmployeePostRequestBody.  # noqa: E501
        :type name: str
        :param description: The description of this EmployeePostRequestBody.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description'
        }

        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'EmployeePostRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EmployeePostRequestBody of this EmployeePostRequestBody.  # noqa: E501
        :rtype: EmployeePostRequestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this EmployeePostRequestBody.


        :return: The name of this EmployeePostRequestBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EmployeePostRequestBody.


        :param name: The name of this EmployeePostRequestBody.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this EmployeePostRequestBody.


        :return: The description of this EmployeePostRequestBody.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EmployeePostRequestBody.


        :param description: The description of this EmployeePostRequestBody.
        :type description: str
        """

        self._description = description
