/**
 * apps-training RESTful API
 * OpenAPI definition file for impulse-apps
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Basic response with application status code
 */
export interface Employee { 
    id?: string;
    name?: string;
    department?: string;
    team?: string;
    mail?: string;
    omitted?: boolean;
    participate?: boolean;
}

